# -*- coding: utf-8 -*-
"""EdgeDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DoMA43H3dHzFvrcDmeVWDyKDuXybRpl
"""

!pip install google-colab

!pip install opencv-python
import cv2
import numpy as np
from google.colab.patches import cv2_imshow

def edge_detection(image_path):
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    img_blur = cv2.GaussianBlur(img, (5, 5), 0)
    edges = cv2.Canny(img_blur, 50, 150)
    cv2_imshow(img)
    cv2_imshow(edges)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
image_path = '/content/360_F_6455661_Ptvg5iAO0DpUlt0ItlO8YewZpvU3IxwX.jpg'
edge_detection(image_path)